name: jobs examples
on:
  push

jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
      - name: configuração do node (pesquisar no marketplace...)
        uses: nodenv/actions/node-version@v3
      - name: verification of node version
        run: node --version
